name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    name: Final Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run full test suite
      run: npm run test:ci
      
    - name: Verify 100% coverage
      run: |
        coverage=$(npm run test:coverage --silent | grep -o "Functions.*[0-9.]*%" | grep -o "[0-9.]*" | head -1)
        if (( $(echo "$coverage < 100" | bc -l) )); then
          echo "❌ Cannot release with coverage below 100% (current: $coverage%)"
          exit 1
        fi
        
    - name: Build package
      run: npm run build
      
    - name: Verify build artifacts
      run: |
        if [ ! -f "dist/index.js" ]; then
          echo "❌ Build verification failed"
          exit 1
        fi

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build package
      run: npm run build
      
    - name: Extract release notes
      id: extract-release-notes
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Generate changelog
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD > CHANGELOG.tmp
        
        # Create release notes
        echo "## Release Notes for v$VERSION" > RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "### Changes" >> RELEASE_NOTES.md
        cat CHANGELOG.tmp >> RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "### Quality Metrics" >> RELEASE_NOTES.md
        echo "- **Test Coverage**: 100% (maintained)" >> RELEASE_NOTES.md
        echo "- **TypeScript**: Strict mode compliance" >> RELEASE_NOTES.md
        echo "- **Security**: No known vulnerabilities" >> RELEASE_NOTES.md
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.extract-release-notes.outputs.version }}
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
        
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Announce release
      uses: actions/github-script@v7
      with:
        script: |
          const version = "${{ steps.extract-release-notes.outputs.version }}";
          
          // Create announcement issue
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `🎉 Release v${version} is now available!`,
            body: `## HQ Rental SDK v${version} Released! 🚀
            
            We're excited to announce the release of HQ Rental SDK v${version}!
            
            ### Installation
            \`\`\`bash
            npm install hq-rental-sdk@${version}
            \`\`\`
            
            ### Highlights
            - ✅ **100% Test Coverage** maintained
            - 🔐 **Security Audited** 
            - 📝 **Full TypeScript Support**
            - 🚗 **Complete HQ Rental API Coverage**
            
            ### Documentation
            - [README](https://github.com/mr-cto/hq-rental-sdk#readme)
            - [Contributing Guide](https://github.com/mr-cto/hq-rental-sdk/blob/main/.github/CONTRIBUTING.md)
            - [API Examples](https://github.com/mr-cto/hq-rental-sdk/tree/main/examples)
            
            Thank you to all contributors who helped make this release possible! 🙏
            `,
            labels: ['announcement', 'release']
          });

  notify-failure:
    name: Notify Release Failure
    runs-on: ubuntu-latest
    needs: [test, release]
    if: failure()
    
    steps:
    - name: Notify on failure
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `❌ Release ${process.env.GITHUB_REF} failed`,
            body: `The release process failed. Please check the [workflow run](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}) for details.`,
            labels: ['release-failure', 'urgent']
          });